#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [[ -n $pid ]]; then
  # If the process is running, send the SIGINT signal to stop it
  pkill -INT -P $pid
else
  echo "Terminated"
fi
