#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd

while IFS=':' read -r username _ userid _ _ home_directory _
do
    echo "$username:$userid:$home_directory"
done < /etc/passwd
