#!/usr/bin/env bash
# This script displays the content of the current directory in a list format, with only the part of the name after the first dash

for file in *
do
    if [ -f "$file" ] && [ "${file:0:1}" != "." ]
    then
        name=${file#*-}
        echo "$name"
    fi
done

